version: "3.3"
services:
 app:
  container_name: checklistcamaras_app 
  build:
   args:
    user: laravel
    uid: 1000
   context: ./
  restart: unless-stopped
  tty: true
  volumes:
   - ./:/var/www/html
  ports:
   - "8000:80"

